services:
  - type: web
    name: stock-advisor
    env: python
    buildCommand: ""
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings